name: Run Databricks Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-databricks-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Trigger Databricks Job
      env:
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST}}
        JOB_ID: ${{ secrets.DATABRICKS_JOBID}}
      run: |
        curl -X POST -H "Authorization: Bearer $DATABRICKS_TOKEN" \
        -v "$DATABRICKS_HOST/api/2.0/jobs/run-now" \
        -d "{\"job_id\": $JOB_ID}"