name: Run Databricks Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-databricks-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Trigger Databricks Job
      env:
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        DATABRICKS_HOST: 'https://adb-7746962439804367.7.azuredatabricks.net/?o=7746962439804367#notebook/23424899253134/command/2236591595819375'
        JOB_ID: '356873846764198'
      run: |
        curl -X POST -H "Authorization: Bearer $DATABRICKS_TOKEN" \
             "$DATABRICKS_HOST/api/2.0/jobs/run-now" \
             -d '{"job_id": $JOB_ID}'