name: Run Databricks Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-databricks-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Install packages
      run: make install

    - name: Trigger Databricks Job
      env:
        DATABRICKS_KEY: ${{ secrets.DATABRICKS_TOKEN }}
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST}}
        DATABRICKS_JOBID: ${{ secrets.DATABRICKS_JOBID}}
      run: 
        make run-workflow